<?php



include "top_menu.php";
include "connect.php";

if (isset($_POST['submit'])) {
  $message = $_POST['message'];
  $insertQuery="INSERT INTO message(message) VALUES ('$message')";

  if($conn->query($insertQuery) ==TRUE){
      header("Location: index.php");
      echo "GOOD";
      exit();

    }else{
      echo "Error: ";
    }
}

?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="index.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"
    ></script>
    <script src="https://cdn.lordicon.com/lordicon.js"></script>
    <title>EcoCycle</title>
  </head>

    <!-- The welcome page -->
  
    
    <div class="hero">
      <h1>Welcome to EcoCycle</h1>
      <p>Quenching Thirst, Preserving Tomorrow</p>
      <p class="tagline">
        Providing sustainable water supply and waste management solutions to
        safeguard the environment and promote a healthier future.
      </p>
      <div class="hero1"></div>
    </div>

    <!-- our services page -->

    <section class="services" id="service">
      <h1>Our Services</h1>
      <div class="service-grid">
        <div class="service-card" style="background-color: #a0b7ec">
          <h4>Portable Water Supply</h4>
          <p>
            We provide clean and safe drinking water to households, industries,
            and institutions.
          </p>
        </div>
        <div class="service-card" style="background-color: #a0b7ec">
          <h4>Water Delivery</h4>
          <p>
            Our team provides water to construction sites, events and ensure
            where water is scare.
          </p>
          <p>Helps to mmet temporary and emergency water needs.</p>
        </div>
        <div class="service-card" style="background-color: #a0b7ec">
          <h4>Water Treatment solutions</h4>
          <p>
            We offer water treatment solutions to remove impurities and
            contaminants, making water safe for consumption.
          </p>
        </div>
        <div class="service-card" style="background-color: #a0b7ec">
          <h4>Water Filtration Systems</h4>
          <p>
            Installing and maintaining Filtration Systems to improve water
            quality and safety.
          </p>
        </div>
      </div>

      <div class="service-grid2">
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Residential Waste Collection</h4>
          <p>
            Collecting household waster,firms residential areas to ensure timely
            and efficient disposal.
          </p>
        </div>
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Commercial Waste Collection</h4>
          <p>
            Provides waste collection, service to business, offices and
            institutions.
            Helping manage their waste efficiently.
          </p>
        </div>
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Industrial Waste Management</h4>
          <p>
            Managing waste generated by industrial process, including
            handling, storage,
            transportation and disposal of industrial waste.
          </p>
        </div>
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Special Waste Disposal</h4>
          <p>
            Handling and disposing of hazardous or toxic waste such as
            chemicals,
            batteries or electronics in accordance with regulation
            and safety standard.
          </p>
        </div>
      </div>

      <div class="service-grid1">
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Dumpster Rentals</h4>
          <p>
            Providing temporary waste storage containers for construction
            sites,events and large-scale clean-ups.
          </p>
        </div>
        <div class="service-card" style="background-color: #e1a86f">
          <h4>Consultation</h4>
          <p>
            Offering expert advices and strategies to help ensure
            business,organization to reduce waste generation and solve
            contaminated and impurities of water to be safe.
          </p>
        </div>
        <div
          class="service-card"
          style="background: linear-gradient(to bottom, #a0b7ec, #e1a86f)"
        >
          <h4>General Education</h4>
          <p>
            Providing education to people to safeguard the environment by good
            disposal and safe water bodies for healthy living.
          </p>
        </div>
      </div>
    </section>

    <!-- communities -->

    <div class="communities">
      <div class="featured-view">
        <h1>FEATURED COMMUNITIES</h1>
        <button><a href="more.html" style="text-decoration: none; color: white;">View All Communities</a></button>
      </div>

      <div class="community-grid">
        <div
          class="community-card"
          style="
            background-image: url(images/Cleaning.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">A</div>
          <p>Ablekuma</p>
          <p class="service">Waste Management</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/people-doing-community-service-by-collecting-trash-outdoors.jpg);
            background-size: cover;
                        background-repeat: no-repeat;
            filter: brightness(0.5);
          "
        >
          <div class="circle">K</div>
          <p>Kotoku</p>
          <p class="service">Waste Management & Water Supply</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/Cleaning.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">N</div>
          <p>Nima</p>
          <p class="service">Waste Management & Water Supply</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/Providing\ urban\ trash.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">T</div>
          <p>Teshie</p>
          <p class="service">Waste Management</p>
        </div>
      </div>
      <button class="btn2"><a href="more.html"  style="text-decoration: none; color: white;">View All Communities</a></button>
    </div>

    <!-- Companies-->

    <div class="companies">
      <div class="featured-view">
        <h1>FEATURED COMPANIES</h1>
        <button><a href="more.html"  style="text-decoration: none; color: white;">View All Communities</a></button>
      </div>

      <div class="community-grid">
        <div
          class="community-card "
          style="
            background-image: url(images/group-different-people-volunteering-foodbank-poor-people.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">M</div>
          <p>Mensoles Ghana</p>
          <p class="service">Water Supply</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/people-working-tech-brand-together.jpg);
            background-size: cover;
            background-repeat: no-repeat;
            filter: brightness(0.5);
          "
        >
          <div class="circle">A</div>
          <p>AIT</p>
          <p class="service">Water Supply</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/different-people-doing-volunteer-work.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">V</div>
          <p>Vista</p>
          <p class="service">Waste Management</p>
        </div>
        <div
          class="community-card"
          style="
            background-image: url(images/Cleaning.jpg);
            background-size: cover;
            filter: brightness(0.5);
          "
        >
          <div class="circle">X</div>
          <p>XBZ</p>
          <p class="service">Waste Management & Water Supply</p>
        </div>
      </div>
      <button class="btn2"><a href="more.html"  style="text-decoration: none; color: white;">View All Communities</a></button>
    </div>

    <!-- About page -->

    <article class="about" id="about">
      <div class="aboutAll about-us">
    <div style="background-image: url(images/icons/Learn-Programming-1--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat; border-left: 4px solid #964B00;" {
      
    }>
       
        </div>

        <div class="firstAbout-div" >
          <h1>About Us</h1>
          <p>
            Welcome to EcoCycle, a leading provider of water supply and waste
            management solutions. Our journey began in 2010, when our founder,
            Edmund Takyi, had a vision to provide clean water and sustainable
            waste management services to communities.

            <br>
            <p>At EcoCycle, we're dedicated to providing essential services that ensure access to clean water and proper waste management. Our mission is to deliver high-quality solutions that promote public health, environmental sustainability, and community well-being.</p>
          </p>
        </div>
      </div>

      <div class="aboutAll our-story">
        <div style="background-image: url(images/icons/Reading-A-Book-3--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat; border-left: 4px solid #964B00;"></div>

        <div  class="secondAbout-div" >
          <h2>Our Story</h2>
          <p>
         

At EcoCycle, we started with a mission to provide clean water and proper waste management to our community. Over time, we've grown into a leading provider of essential services that promote public health, environmental sustainability, and community well-being.

We began with a passion for making a difference and built a team of experts who share our vision. As we grew, we expanded our services to meet the evolving needs of our clients. Today, we offer a range of solutions, including:
<br>
<br>
<ul>
  <li>Potable water supply</li> 
<li> Water treatment</li> 
<li> Waste collection</li>
<li>And more</li> 
</ul>



<p>We've invested in state-of-the-art equipment and technology to ensure our services are efficient, reliable, and environmentally friendly.</p>
          </p>
          <p>
            However, our team's determination and commitment to our mission kept
            us moving forward. We worked tirelessly to develop innovative
            solutions to the water and waste management challenges faced by our
            community.
          </p>
        </div>
      </div>

      <div class="aboutAll mission">
        <div style="background-image: url(images/icons/Refill-Energy-2--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat; border-left: 4px solid #964B00;"></div>

        <div class="thirdAbout-div">
          <h2>Our Mission</h2>
          <p>
  At EcoCycle, our mission is to provide clean water and effective waste management solutions that promote public health, environmental sustainability, and community well-being. We're dedicated to delivering exceptional service, investing in innovative technologies, and building strong relationships with our clients and the community. <br>

Our Goals 

<ul>
   <li>To ensure access to clean and safe water for all our clients.</li>
<li>To provide efficient and reliable waste management services that minimize environmental impact.</li>
 <li>To promote sustainability and environmental responsibility in everything we do.</li>
<li>To build trust and loyalty with our clients through exceptional service and support. </li>

</ul>
<p>We're committed to making a positive impact in our community and promoting a healthier, more sustainable future for all.</p>
          </p>
        </div>
      </div>

      <div class="aboutAll values">
        <div style="background-image: url(images/icons/Recycle-4--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat; border-left: 4px solid #964B00;"></div>

        <div class="fouthAbout-div">
          <h2>Our Values</h2>
          <ul>
            <li>Environmental sustainability</li>
            <li>Social responsibility</li>
            <li>Customer satisfaction</li>
            <li>Innovation</li>
            <li>Teamwork</li>
          </ul>
        </div>
      </div>

      <div class="aboutAll achievement">
        <div style="background-image: url(images/icons/Graduation-3--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat; border-left: 4px solid #964B00;"></div>

        <div class="fifthAbout-div">
          <h2>Achievements</h2>
          <p>
            Over the years, we have achieved numerous milestones, including:
          </p>
          <ul>
            <li>Providing clean water to over 100,000 people</li>
            <li>Reducing waste disposal by 50% in our service areas</li>
            <li>
              Implementing sustainable waste management practices in over 50
              communities
            </li>
            <li>
              Receiving numerous awards for our environmental sustainability
              initiatives
            </li>
          </ul>
        </div>
      </div>

      <div class="aboutAll moving">
        <div style="background-image: url(images/icons/Leadership-3--Streamline-Brooklyn.png );background-size: contain; background-position: center;background-repeat: no-repeat;  border-left: 4px solid #964B00;"></div>

        <div class="sixthAbout-div">
          <h2>What Keeps Us Moving</h2>
          <p>
            Our passion for environmental sustainability and social
            responsibility drives us to continue innovating and improving our
            services. We are committed to making a positive impact on the lives
            of our customers and the environment.
          </p>

          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium ad sint est nulla at tenetur adipisci reiciendis? Quasi voluptatibus sapiente sequi, corrupti, velit quo molestias amet impedit, maiores ipsam cupiditate?</p>
        </div>
      </div>
    </article>

    <div class="template"></div>

    <footer>
      <div class="footer-div">
        <div>
          <p>Ghana</p>
          <p>Accra</p>
          <p>Kwashieman</p>
          <p>Phone</p>
          <pre>
+233 596 862 641
+233 201 036 960
     </pre
          >
        </div>

        <div class="footer-div2">
          <h5>Menu & Links</h5>
          <p><a href="#">Home</a></p>
          <p><a href="#">Services</a></p>
          <p><a href="#">Blog</a></p>
          <p><a href="#">About Us</a></p>
          <p><a href="#">Contact us</a></p>
        </div>

        <div class="footer-div3">
          <form action="" method="post">
          <h5>Count On Us</h5>

    
          <input type="text" name="message" placeholder="Count on us" id="input-field" />
         
     <button type="submit" name= "submit">Submit</button>
          
     </form>
        </div>
      </div>

      <div class="copy-right">
        <p>&copy; 2025 EcoCycle. All Right Reserved</p>
      </div>
    </footer>
  </body>
</html>
